# action.yml
name: 'DMI5 Checker'
author: 'AffectedArc07'
description: 'Ensures no DMI5 icons exist in a codebase'
inputs:
  icons-path:
    description: 'Path to your icons directory'
    required: false
    default: 'icons'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.icons-path }}
branding:
  icon: 'coffee' # yes
  color: 'green'
